server:
  port: 8888

spring:
  application:
    name: gcwconfig

  cloud:
    config:
      server:
        #        native:
        #          search-locations: file:///C://work//git-local-repo
        git: #default
          uri: https://github.com/dron512/spring-cloud-config
          default-label: main
        bootstrap: true
