FROM eclipse-temurin:17-jdk-jammy
# or
# FROM openjdk:8-jdk-alpine
# FROM openjdk:11-jdk-alpine

# CMD ["./gradlew", "clean", "build"]
# or Maven 
CMD ["./mvnw clean && ./mvnw", "package","-Dmaven.test.skip=true"]

# VOLUME /tmp

# ARG JAR_FILE=build/libs/*.jar
# or Maven
ARG JAR_FILE_PATH=target/*.jar

COPY ${JAR_FILE} app.jar

EXPOSE 10000

ENTRYPOINT ["java","-jar","-Dserver.port=10000","/app.jar"]