insert into users (email, gender, password, username, wdate) values ('aaa@naver.com', 'MALE', '12341234', '홍길동', now());
insert into users (email, gender, password, username, wdate) values ('bbb@naver.com', 'MALE', '12341234', '홍길당', now());
insert into users (email, gender, password, username, wdate) values ('ccc@naver.com', 'MALE', '12341234', '홍길딩', now());
insert into users (email, gender, password, username, wdate) values ('ddd@naver.com', 'MALE', '12341234', '김길동', now());
insert into users (email, gender, password, username, wdate) values ('eee@naver.com', 'MALE', '12341234', '김길당', now());
insert into users (email, gender, password, username, wdate) values ('fff@naver.com', 'MALE', '12341234', '김길딩', now());
insert into users (email, gender, password, username, wdate) values ('ggg@naver.com', 'MALE', '12341234', '이길동', now());
insert into users (email, gender, password, username, wdate) values ('hhh@naver.com', 'MALE', '12341234', '이길당', now());
insert into users (email, gender, password, username, wdate) values ('iii@naver.com', 'MALE', '12341234', '이길딩', now());